name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web artifacts Docusaurus
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out latest changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm install
      
      - name: Build web assets
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy assets
        id: deployment
        uses: actions/deploy-pages@v4